export const SET_FILTER = 'SET_FILTER';
export const SET_TODOS  = 'SET_TODOS';
export const ADD_TODO   = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const REMOVE_ALL_TODO = "REMOVE_ALL_TODO";
export const COMPLETE_STATUS = "COMPLETE_STATUS";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";